name: sknat

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      HOSTNAME: 0.0.0.0
      WEB_API_BASE_URL: http://host.docker.internal:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
